### ISSUE TITLE
Make CDN DNS configs dynamic in http distribution

### ISSUE THREAD

**Issue by janibashamd** [f5devcentral/xcwaapcdnguide#2]
If we look at line 132 in waap-cdn-http.yaml, we see code "dns_volterra_managed: False" which is static and should be updated to fetch this details from env var "dns_volterra_managed". 

Because of above issue, if domain is volterra managed CDN is getting created but "Automatically Manage DNS Records" field is not getting set causing issues.

**Comment by yoctoalex** [comment]
Hello,

Thank you for the feedback. The issue has been fixed.


Thanks,
Alex

**Comment by janibashamd** [comment]
Looks good from my side so closing this..
